FROM	debian:buster

RUN		apt-get update && apt-get -y install \
		nginx \
		openssl \
		php-fpm \
		php-mysql \
		php-mbstring \
		mariadb-server \
		vim \
		wget

COPY	./srcs/run.sh ./
COPY	./srcs/default ./srcs/
COPY	./srcs/config.inc.php ./srcs/
COPY	./srcs/wp-config.php ./srcs/

EXPOSE	80 443

CMD		bash run.sh
